/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CorsHeaders {
    #[serde(rename = "access-control-allow-origin", skip_serializing_if = "Option::is_none")]
    pub access_control_allow_origin: Option<String>,
    #[serde(rename = "access-control-allow-methods", skip_serializing_if = "Option::is_none")]
    pub access_control_allow_methods: Option<String>,
    #[serde(rename = "access-control-allow-headers", skip_serializing_if = "Option::is_none")]
    pub access_control_allow_headers: Option<String>,
    #[serde(rename = "access-control-max-age", skip_serializing_if = "Option::is_none")]
    pub access_control_max_age: Option<String>,
}

impl CorsHeaders {
    pub fn new() -> CorsHeaders {
        CorsHeaders {
            access_control_allow_origin: None,
            access_control_allow_methods: None,
            access_control_allow_headers: None,
            access_control_max_age: None,
        }
    }
}


