/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ErrValidation : Specific error details related to invalid / missing request parameters



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ErrValidation {
    /// Message providing context on the rule / property that failed validation
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    /// Relevant property or rule in the schema associated with failure message
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl ErrValidation {
    /// Specific error details related to invalid / missing request parameters
    pub fn new() -> ErrValidation {
        ErrValidation {
            message: None,
            key: None,
        }
    }
}


