/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GroupsRequest {
    /// Name of a log group.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Query that determines the data that is visible to members of a group.
    #[serde(rename = "accessScopes", skip_serializing_if = "Option::is_none")]
    pub access_scopes: Option<String>,
}

impl GroupsRequest {
    pub fn new() -> GroupsRequest {
        GroupsRequest {
            name: None,
            access_scopes: None,
        }
    }
}


