/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// KeyType : The type of the key

/// The type of the key
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum KeyType {
    #[serde(rename = "ingestion")]
    Ingestion,
    #[serde(rename = "service")]
    Service,

}

impl ToString for KeyType {
    fn to_string(&self) -> String {
        match self {
            Self::Ingestion => String::from("ingestion"),
            Self::Service => String::from("service"),
        }
    }
}

impl Default for KeyType {
    fn default() -> KeyType {
        Self::Ingestion
    }
}




