/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ListUsageAppV2200Response {
    /// The calculated starting time (exclusive) used internally.
    #[serde(rename = "from", skip_serializing_if = "Option::is_none")]
    pub from: Option<String>,
    /// The calculated ending time (exclusive) used internally.
    #[serde(rename = "to", skip_serializing_if = "Option::is_none")]
    pub to: Option<String>,
    #[serde(rename = "results", skip_serializing_if = "Option::is_none")]
    pub results: Option<Vec<crate::models::ListUsageAppV2200ResponseResultsInner>>,
}

impl ListUsageAppV2200Response {
    pub fn new() -> ListUsageAppV2200Response {
        ListUsageAppV2200Response {
            from: None,
            to: None,
            results: None,
        }
    }
}


