/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Method : WebHook method such as POST.

/// WebHook method such as POST.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Method {
    #[serde(rename = "POST")]
    Post,
    #[serde(rename = "PUT")]
    Put,
    #[serde(rename = "PATCH")]
    Patch,

}

impl ToString for Method {
    fn to_string(&self) -> String {
        match self {
            Self::Post => String::from("POST"),
            Self::Put => String::from("PUT"),
            Self::Patch => String::from("PATCH"),
        }
    }
}

impl Default for Method {
    fn default() -> Method {
        Self::Post
    }
}




