/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Role : role of member. Owner shall not be created or set through api

/// role of member. Owner shall not be created or set through api
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Role {
    #[serde(rename = "owner")]
    Owner,
    #[serde(rename = "admin")]
    Admin,
    #[serde(rename = "readonly")]
    Readonly,
    #[serde(rename = "member")]
    Member,

}

impl ToString for Role {
    fn to_string(&self) -> String {
        match self {
            Self::Owner => String::from("owner"),
            Self::Admin => String::from("admin"),
            Self::Readonly => String::from("readonly"),
            Self::Member => String::from("member"),
        }
    }
}

impl Default for Role {
    fn default() -> Role {
        Self::Owner
    }
}




