/*
 * Log Analysis API
 *
 * *REST API to send log data, export data and manage configuration*  To utilize the inline testing functionality here, please go into your Mezmo account and add the following address to your CORS Origins page: `https://docs.mezmo.com`. 
 *
 * The version of the OpenAPI document: 2.1
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct StreamConfigRequestAllOf {
    /// Password in provided credentials to authorize access to brokers
    #[serde(rename = "password")]
    pub password: String,
}

impl StreamConfigRequestAllOf {
    pub fn new(password: String) -> StreamConfigRequestAllOf {
        StreamConfigRequestAllOf {
            password,
        }
    }
}


